---

- include: "define-home.yml"
  tags:
    - tomcat8
    - tomcat8-config
    - tomcat8-install
  
- include: "install-{{ ansible_os_family }}.yml"
  tags:
    - tomcat8
    - tomcat8-install

- include: config.yml
  static: no
  tags:
    - tomcat8
    - tomcat8-config
